# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_source', models.TextField(blank=True, null=True)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_description', models.TextField(blank=True, null=True)),
                ('news_date', models.TextField(blank=True, null=True)),
                ('news_author', models.TextField(blank=True, null=True)),
                ('news_image', models.TextField(blank=True, null=True)),
                ('news_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wheater_satus',
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_citykey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_dailyforecasts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_today',
            field=models.TextField(blank=True, null=True),
        ),
    ]
