# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0002_auto_20171214_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wheater_degree',
            field=models.CharField(default='celsius', max_length=10),
        ),
    ]
