# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 15:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0004_news_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='news_title'),
        ),
    ]
