# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 15:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0005_auto_20171215_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='news_title', unique=True),
        ),
    ]
