# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0008_auto_20171216_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
    ]
