# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0011_auto_20171219_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
