# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0012_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
