# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 19:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0016_auto_20171219_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
