# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0017_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chiplist',
            field=models.TextField(blank=True, default="[{tag: 'General'},{tag: 'Technology'},{tag: 'Business'},{tag: 'Gaming'},{tag: 'Sport'},{tag: 'Politics'}]", null=True),
        ),
    ]
