# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0020_auto_20171223_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chiplist',
        ),
        migrations.AddField(
            model_name='profile',
            name='chip_business',
            field=models.TextField(blank=True, default='true', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chip_general',
            field=models.TextField(blank=True, default='true', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chip_politics',
            field=models.TextField(blank=True, default='true', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chip_sport',
            field=models.TextField(blank=True, default='true', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chip_technology',
            field=models.TextField(blank=True, default='true', null=True),
        ),
    ]
