# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0021_auto_20171223_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chip_gaming',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chip_business',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chip_general',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chip_politics',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chip_sport',
            field=models.TextField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chip_technology',
            field=models.TextField(blank=True, default='True', null=True),
        ),
    ]
