# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flato', '0022_auto_20171223_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numberofitems',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
